bradymholt/cRonstrue

- _config.yml
- src/cronParser.ts
- test/cronstrue.js
> Fix regex issue with DOW when dayOfWeekStartIndexZero = true

- .vscode/launch.json
- test/cronstrue.ts
- test/i18n.ts
- Fix vscode launch debugger config
- Use this.test.title to DRY up test asserts
> Test improvements

- .vscode/settings.json
- src/expressionDescriptor.ts
- src/i18n/locale.ts
- src/i18n/locales/de.ts
- src/i18n/locales/en.ts
- src/i18n/locales/es.ts
- src/i18n/locales/fr.ts
- src/i18n/locales/it.ts
- src/i18n/locales/nb.ts
- src/i18n/locales/nl.ts
- src/i18n/locales/pl.ts
- src/i18n/locales/pt_BR.ts
- src/i18n/locales/ro.ts
- src/i18n/locales/ru.ts
- src/i18n/locales/sv.ts
- src/i18n/locales/tr.ts
- src/i18n/locales/uk.ts
- src/i18n/locales/zh_CN.ts
- test/cronstrue.ts
> Fix: Last day of the month shows as "L of the month" in lists and intervals

- src/expressionDescriptor.ts
- src/i18n/locale.ts
- src/i18n/locales/de.ts
- src/i18n/locales/en.ts
- src/i18n/locales/es.ts
- src/i18n/locales/fr.ts
- src/i18n/locales/it.ts
- src/i18n/locales/nb.ts
- src/i18n/locales/nl.ts
- src/i18n/locales/pl.ts
- src/i18n/locales/pt_BR.ts
- src/i18n/locales/ro.ts
- src/i18n/locales/ru.ts
- src/i18n/locales/sv.ts
- src/i18n/locales/tr.ts
- src/i18n/locales/uk.ts
- src/i18n/locales/zh_CN.ts
- test/cronstrue.ts
> Implement last day offset support

- webpack.config.js
> Allow for portable AMD modules in the browser

- package.json
To get rid of the really annoying GH alert.
> Bump @types/chai dep

- src/i18n/locales/de.ts
> Updating German translation for daily jobs

- src/i18n/locales/de.ts
This reverts commit f3da9d15d2656dc2ed221caa0654beecc7d13dca.
Fixes #65
> Revert "Updating German translation for daily jobs"

- src/i18n/locales/ja.ts
The order of the days of week was wrong.
So I corrected it.
> Fix ja translations of daysOfTheWeek

- RELEASING.md
- package-lock.json
- package.json
Reverts bradymholt/cRonstrue#75
> Revert "Bump dependencies to latest versions"

- RELEASING.md
- package-lock.json
- package.json
Reverts bradymholt/cRonstrue#77
> Revert "Revert "Bump dependencies to latest versions""

- src/cronParser.ts
- src/expressionDescriptor.ts
- test/cronstrue.ts
- test/i18n.ts
> Fix parsing minute range with interval

- src/cronParser.ts
- src/expressionDescriptor.ts
- test/cronstrue.ts
> Fix extra comma when minutes = 0

- README.md
- src/i18n/allLocales.ts
- src/i18n/locales/sw.ts
I have added kiswahili locale
Hopefully it will be helpful like it was for me.
> Added Kiswahili locale

- README.md
- package-lock.json
- src/i18n/allLocales.ts
- src/i18n/locales/da.ts
- src/i18n/locales/sl.ts
- test/i18n.ts
Fixes https://github.com/bradymholt/cRonstrue/issues/96
> Fix Danish and Slovenian translations (in code but not exported)

- src/expressionDescriptor.ts
- test/cronstrue.ts
> Fix hour interval at 0 minutes past the hour

- CONTRIBUTING.md
- package.json
- src/i18n/locales/nb.ts
- test/i18n.ts
A few of the Norwegian translations were a bit "off", and there were some typos here and there that I fixed. In addition "npm start" did not work, so I added that aswell. Added some new tests to cover the translation changes.
> Fixed Norwegian translations + minor typos

- src/i18n/locales/de.ts
There were two untranslated phrases that I fixed
> translate English phrases into German

- .gitignore
- src/expressionDescriptor.ts
- src/i18n/locale.ts
- src/i18n/locales/zh_CN.ts
- src/i18n/locales/zh_TW.ts
- test/i18n.ts
Correct and adapt Chinese translation zh_CN & zh_TW translation. Make the generated description more Chinese.
修正和适配中文翻译。让其生成的描述更像中国人。
> Collect zh_CN & zh_TW translations

- i18n.d.ts
- webpack.config.js
- Only minify .min files
- Fix type definitons for `import cronstrue from "cronstrue/i18n";`
> Misc fixes

- src/i18n/locales/fi.ts
A couple more of Finnish changes (just missing spaces)
> Update Finnish locale

- .github/workflows/build.yml
- package-lock.json
- package.json
- Install missing uglifyjs-webpack-plugin
- Fix dupe Actions run - only trigger for pushes to master and let pull_request trigger handle pushed on PRs
> Fix more build issues

- src/cronParser.ts
- test/cronstrue.ts
Do not convert 1/ to */ for DOW because 1/ means start on Monday
Fixes #127
> Do not convert 1/ to */ for DOW

- src/cronParser.ts
- test/cronstrue.ts
see： test cases  "empty_around_comma"  and "empty_side_by_comma"
> fix: should ignore empty charaters around comma

- src/cronParser.ts
Remove usage of chai and implement `assert` manually.
Fixes #175
> Remove usage of chai

- src/cronParser.ts
- test/cronParser.ts
- test/cronstrue.ts
> Fix detection of 6 part (w/ year) when * is specified for year

- package-lock.json
- src/expressionDescriptor.ts
- test/cronstrue.ts
> Do not convert hour segment :00 to :59 if the range is "on the hour"

- .gitignore
- README.md
- src/i18n/allLocales.ts
- src/i18n/locales/pt_PT.ts
- test/i18n.ts
Hi :),
This PR adds the missing pt_PT ( portuguese Portugal ) locale translations.
Thanks, best regards and congrats for the great lib :).
POFerro
> Add locale for pt_PT (portuguese Portugal)

- src/cronstrue.ts
- src/expressionDescriptor.ts
just add funtion toDetails() & property parseDetails
toDetails() will return a object like
```js
parseDetails: {
full: "At 09:03:01 AM, only on Tuesday, only in 2022"
hour: " 09"
min: "03"
mon: ""
mond: ""
sec: "01"
wkd: ", only on Tuesday"
year: ", only in 2022"
}
```
it can help us to get the more detailed description
hope it can be applied to more complex business requirement scenarios
> feat: a more detailed description

- src/expressionDescriptor.ts
- src/i18n/locale.ts
- src/i18n/locales/en.ts
> Add correct handling of DOW when DOM is present

- docs/index.html
- docs/template.hbs.html
Thanks for the good library.
It is difficult to check the locales setting on the demo page, so I suggest adding it.
> [Suggesstion] support locales on demo page

- src/i18n/locales/ru.ts
fix range description for month and year at ru locale
> fix optional types and undefined string

- webpack.config.js
> Fix loading locale in browser

- src/i18n/locales/fr.ts
- test/i18n.ts
> fr locale set use24HourTimeFormat to true

- README.md
- src/i18n/allLocales.ts
- src/i18n/locales/my.ts
- test/i18n.ts
Hi!
Adding `my` Malay (Malaysia) Locales to the mix.
Cheers!
> feat: Add Malay (Malaysia) Locale

- src/expressionDescriptor.ts
- test/cronstrue.ts
> feat: Added support for floating point tzOffset

- src/i18n/locales/ar.ts
- src/i18n/locales/be.ts
- src/i18n/locales/ca.ts
- src/i18n/locales/es.ts
- src/i18n/locales/fi.ts
- src/i18n/locales/hu.ts
- src/i18n/locales/id.ts
- src/i18n/locales/ja.ts
- src/i18n/locales/nb.ts
- src/i18n/locales/nl.ts
- src/i18n/locales/pt_BR.ts
- src/i18n/locales/sw.ts
- src/i18n/locales/vi.ts
- src/i18n/locales/zh_TW.ts
- test/i18n.ts
This PR fixes the issues described in https://github.com/bradymholt/cRonstrue/issues/303. Corresponding tests were updated.
> Fixed time formats for various locales

- src/i18n/locales/nl.ts
> Dutch - "Op" to "Om" per feedback

- docs/index.html
resolves #339
This PR:
- Prevents page refresh when submitting the form (pressing <kbd>Enter</kbd>)
- Automatically translates when the language option changes
> fix(playground): prevent page refresh on submit
