dist/cronstrue.d.ts
Updated the typings file to use `default` instead of `=` as this seems to be the way to export modules. Was getting errors trying to use this package with Angular-CLI.
Closes #17
=> Changed typings file to use default

webpack.config.js
This fixes an issue with the UMD build that was caused by the recent upgrade to Webpack 4.  There is an outstanding [Webpack 4 UMD bug](https://github.com/webpack/webpack/issues/6522) that needs to be worked around to avoid a `window` reference in the output.
Fixes https://github.com/bradymholt/cRonstrue/issues/76
=> Fix "window is not defined" when requiring in Node

src/cronParser.ts, test/cronParser.ts
Came across this issue today.  Looks like the cron-expression-descriptor this was ported from uses the "remove empty elements" flag in their split but since JS doesn't have that, I thought splitting on a regex was the best solution.
=> change parser to split on one or more spaces between parts

README.md, package-lock.json, package.json, src/expressionDescriptor.ts, src/i18n/allLocales.ts, src/i18n/locale.ts, src/i18n/locales/ko.ts, test/i18n.ts
At Korean language PM/AM part of time expression goes at the beginning of the string: for example, PM hh:mm. Apart from that, it should be translated to Korean accordingly:
PM -> 오후
AM -> 오전
Extended interface of Locale with optional methods to expose flag controlling position of time period and translation of it:
- setPeriodBeforeTime
- am
- pm
If they are not provided default values are used:
- false
- AM
- PM
So the changes are back-word compatible.
Translations are provided by native Korean speaker.
=> Added support for Korean language

src/i18n/locales/fi.ts
The `spaceAnd()` and `spaceAndSpace()` functions are missing the spaces. I don't really know Finnish but when using your library in a personal project I run into this and checked with Google translate. 
I also compared it with the same functions in other languages and the spaces are indeed missing here.
=> Update Finnish translation

src/i18n/locales/de.ts
commaOnlyOnX0 and commaAndOnX0 changed so they clearly read as EVERY selected-day, commaOnDayX0OfTheMonth changed so grammar is more correct
=> Clarifying phrasing

src/expressionDescriptor.ts, test/cronParser.ts, test/cronstrue.ts
Fixes #124 
This is my first pass. Unfortunate, the requested wording was not compatible with established patterns in the library. 
- Requested: "Every 10 minutes from 5th minutes to 45th minute, every 5 minutes, at 9th minute"
- Actual: "Every 10 minutes, minutes 5 through 45 past the hour, every 5 minutes, at 9 minutes past the hour"
This was accomplished by splitting the expression on the comma and iteratively calling `getSegmentDescription` for each segment. So each segment is translated as it would be if it were the entire expression.
The downside to this approach is that "minutes 5 through 45 past the hour" is a little unclear. I am open to suggestions as to how to improve that (e.g. potentially joining the segments with semi-colons, "Every 10 minutes, minutes 5 through 45 past the …
=> Fix complex parsing for minutes

README.md
Documenting `{ verbose: true }` feature would be useful, as said in https://github.com/bradymholt/cRonstrue/issues/128
See how rendered `README.md` looks like [here](https://github.com/Duwab/cRonstrue#usage)
=> Add an example of `verbose` usage

README.md, dist/cronParser.d.ts, dist/expressionDescriptor.d.ts, dist/options.d.ts, dist/rangeValidator.d.ts, src/cronParser.ts, src/expressionDescriptor.ts, src/options.ts, src/rangeValidator.ts, test/cronstrue.ts
Fixes #209
This PR will add support for `monthStartIndexZero`. By default this value will be set to false i.e JAN=1 and DEC=12. If it is set to `true` then JAN=0 and DEC=11.
This code pretty much copies `dayOfWeekStartIndexZero` with a small difference in the regex which now has `\d{1,2}` as number of digits in a month can be 1 or 2.
I also added test for some happy case and for validation.
=> add support for monthStartIndexZero

README.md, webpack.config.js
This PR corrects a few problems that happened due to #230:
1. Minification did not work as expected - everything was minified instead only `.min` files.
2. All single locale files contains the whole cronstrue code. Importing `es` + `fr` would result in twice the size, hence the whole split that was done in the first place did not mean anything size-wise.
3. Updated README to showcase all situations
=> Corrected packaging of locales to import base module and updated README (Fixes #230)

src/i18n/locales/fr.ts
French has a missing translation for commaEveryX0DaysOfTheWeek
Also updated commaStartingX0 to have a more french meaning
=> Update french language

src/i18n/locales/ko.ts
0 0 1 * *
en : At 12:00 AM, on day 1 of the month
ko : **_에서_** 오전 12:00, 해당 월의 1일에 (unnatural sentence)
ref. [cron-expression-descriptor](https://github.com/bradymholt/cron-expression-descriptor/blob/a3e31b3bc8fc2cd9f93d5d24e9ecdcd63a82fafd/lib/Resources.ko.resx#L139)
=> Update Korean words for 'at'

src/expressionDescriptor.ts, src/i18n/locale.ts, src/i18n/locales/ru.ts, test/i18n.ts
Word formation is complex In Russian and other Slavic languages. For example, */21, */22, */25 (minutes) - кажд**ую** 21 мину**ту**, кажд**ые** 22 мину**ты**, кажд**ые** 25 мину**т**. Or "Sunday through Tuesday" is "**с** воскресенья по вторни**к**", but "Tuesday through Friday" is "**со** вторни**ка** по пятницу".
I have added optional arguments to some functions and use it in ru locale. It may be helpful for _be, uk_ and some other locales.
=> Fix ru locale

README.md, bin/cli.js, package.json
```
$ npm install -g cronstrue
$ cronstrue 1 2 3 4 5
At 02:01 AM, on day 3 of the month, and on Friday, only in April
$ cronstrue 1 2 3
Error: too few arguments (3): 1 2 3
Usage (5 args): cronstrue minute hour day-of-month month day-of-week
or
Usage (6 args): cronstrue second minute hour day-of-month month day-of-week
or
Usage (7 args): cronstrue second minute hour day-of-month month day-of-week year
```
=> Add cronstrue binary

src/i18n/locales/zh_TW.ts
Hi!
I add space between variables and adjust some translate mistakes.
Original:
產生`正規表達式`描述時發生了錯誤，請檢查 cron 表達式語法。
it translates `expression`  to `regular expression`, but it is cron expression.
=> fix zh_TW locale

src/expressionDescriptor.ts, test/cronstrue.ts
fix #199
I have moved the code that adds numeric prefixes (first, second, etc) to the `getSingleItemDescription`. It was previously in the `getDescriptionFormat` and tried to find correct prefix for e.g. `#3,1#2`, because it took only the first weekday into consideration.
The code diff looks crazy, but if you take a closer look then you will se that I only moved the `switch` statement to another method and concatenated properly.
It seems to fix the problem and does not break any tests :-)
=> Fix multiple days of week outputs null

src/i18n/locales/pt_BR.ts, test/i18n.ts
This pull request addresses an issue where double occurrences of "de" were introduced during the conversion of certain cron expressions to text in the pt_BR locale. The proposed changes ensure that the double "de" is prevented, specifically when a range is present at the beginning of the string.
| expression | response | expected |
| ---- | --------- | ---------- |
| * * * 1-4,7 | somente de de segunda-feira a sexta-feira e domingo | somente de segunda-feira a sexta-feira e domingo|
| * * * 1-4,6 * | a cada dia, somente em de janeiro a abril e junho | a cada dia, somente de janeiro a abril e junho |
=> If string has a range in first interval don't render "de"

src/cronParser.ts, test/cronstrue.ts
Add relevant test under the 'At' section
=> Ordering days on parse()

src/cronParser.ts, test/cronstrue.ts
Fixes https://github.com/bradymholt/cRonstrue/issues/309
=> Specify "cron" in error message

src/i18n/locales/ko.ts
fixed awkward Korean description
=> fix: awkward Korean description

src/i18n/locales/en.ts, src/i18n/locales/zh_CN.ts, src/i18n/locales/zh_TW.ts
As described in #272, when both DOM and DOW present, the default behavior of cron will schedule on both matches.
And this is also commented in the source code as: https://github.com/bradymholt/cRonstrue/blob/main/src/expressionDescriptor.ts#L388
So I changed the language to express the correct meaning.
Since I can only speak `zh` and `en`, I only did changes in these files:
* en.ts
* zh_CN.ts
* zh_TW.ts
=> fix: wrong word when DOM and DOW both present (#272)

README.md, src/cronParser.ts, test/cronParser.ts, test/cronstrue.ts
Added support for '@' expressions. 
@yearly       = `0 0 1 1 *` 
@annually   = `0 0 1 1 *` 
@monthly    = `0 0 1 * *` 
@weekly      = `0 0 * * 0` 
@daily          = `0 0 * * *` 
@midnight   = `0 0 * * *` 
@hourly        = `0 * * * *` 
The @ expressions gots translated in a basic cron and given to the origin parse function. Let me know what you think.
=> Support for '@' expressions

src/expressionDescriptor.ts, src/i18n/locale.ts, src/i18n/locales/pt_BR.ts, src/i18n/locales/pt_PT.ts, test/i18n.ts
Hello! This pull request addresses a grammatical issue in the Portuguese translation of weekdays and weekends.
In Portuguese, weekdays are grammatically feminine, while weekends are masculine. Currently, the output does not reflect this distinction, leading to incorrect gender usage in some translations.
Example
Given the following cron expression:
`45 10 * * 6#2`
(At 10:45 AM, on the second Saturday of the month)
Expected Output:
`"Às 10:45, no segundo sábado do mês"`
Actual Output:
`"Às 10:45, na segunda sábado do mês"`
This PR corrects the gender agreement for weekend days, ensuring accurate and grammatically correct translations.
Thank you for your consideration!
=> [i18n] fix masculine and feminine forms of the weekdays in PT

src/expressionDescriptor.ts, src/i18n/locale.ts, src/i18n/locales/fr.ts, test/i18n-fr.ts
In #337 we discussed about "de le" should be "du" in French, this has been commited as "de" (in #338) for other cases but I encountered some other cases where "le" was missing for days of week crons.
This is a lightweight fix that works correctly but `src/expressionDescriptor.ts` contains a special case for french to replace "de le" to "du" and I cannot figure ou how to do that properly without editing all locales to add a custom method. I wanted to keep it simple.
Feel free to give some feedback or commit to this PR if you have something better :) Thanks
=> Add workaround for french periods & fix side effect with previous change

src/expressionDescriptor.ts, test/cronstrue.ts
This merge request addresses the issue described in #294, where multiple hour ranges in a cron expression were not being interpreted correctly. Specifically, the end of each hour range was incorrectly formatted as :00 instead of :59 for the last minute of the range.
All tests have been run and passed successfully after applying this fix. If the proposed solution does not align with your vision for the library or if you prefer a different approach, feel free to close this merge request or update it as you see fit. Thank you for maintaining this great library!
=> Fix: Incorrect Multiple Range Hour Interpretation (#294)

src/expressionDescriptor.ts, src/options.ts
`tzOffset` was deprecated in https://github.com/bradymholt/cRonstrue/pull/336 and removed here.
=> Remove support for `tzOffset` option

bin/cli.js, test/cli-special-syntax.js
- Add ability to parse single argument expressions including @ syntax in the CLI
- Enhance usage text with examples of @ syntax and quoted expressions
- Maintain backward compatibility with space-separated arguments format
- Extends and completes work done in https://github.com/bradymholt/cRonstrue/pull/318
This enables tools like [cronex.nvim](https://github.com/fabridamicelli/cronex.nvim) to use the CLI for translating special @ syntax expressions like @daily and @monthly as seen in https://github.com/fabridamicelli/cronex.nvim/pull/8.
Manual testing confirms that all special @ syntax formats and normal cron expressions work correctly:
```
Expression: @daily
Description: At 12:00 AM
--------------------------------------------------
Expression: @weekly
Description: At 12:00 AM, only on …
```
=> feat: add support for @ syntax expressions in CLI

README.md, src/cronParser.ts, src/expressionDescriptor.ts, src/i18n/locale.ts, src/i18n/locales/en.ts, test/cronParser.ts, test/cronstrue.ts
- Added support for the missing `@reboot` syntax, which is commonly used in cron implementations
- Added `@reboot` to the list of supported special expressions in the CronParser class
- Created a special handler to return "At system startup" for @reboot in the ExpressionDescriptor
- Added comprehensive tests for the new functionality
- Updated README to document the @reboot support
- Added unit tests for both CronParser and ExpressionDescriptor classes
- Manual testing with various expressions to ensure compatibility with existing features
=> Add support for @reboot special syntax
